version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "9001:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yoo
      MYSQL_DATABASE: app_db
      MYSQL_USER: gosman
      MYSQL_PASSWORD: yoo
    volumes:
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: "lucas-sandery"
    links:
      - db